### ISSUE TITLE
How to get DFF Dataset?

### ISSUE THREAD

**Issue by Koruvika** [OpenRL-Lab/DeepFakeFace#2]

**Comment by Koruvika** [comment]
It seems like I have to run several code files to get the DFF dataset?

**Comment by huangshiyu13** [comment]
You need to download the dataset from huggingface: https://huggingface.co/datasets/OpenRL/DeepFakeFace/tree/main

**Comment by Koruvika** [comment]
I have downloaded dataset successfully. Thank for reply!
